[2020-05-01 13:14:35,612] - [ERROR] - [{"error_msg": "The API does not exist or has not been published in the environment", "error_code": "APIGW.0101", "request_id": "c9ac385bb3d422e281b34e7d871134b3"}]
[2020-05-01 13:39:24,807] - [ERROR] - [Error occurs in getting token, {"error":{"code":401,"message":"The username or password is wrong.","title":"Unauthorized"}}]
[2020-05-01 13:40:29,579] - [INFO] - [websocket open]
[2020-05-01 14:00:58,262] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis.cn-north-1.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1.0/voice/tts (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F306A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2020-05-01 14:01:09,295] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis.cn-north-1.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1.0/voice/tts (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F30640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2020-05-01 14:01:09,299] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis.cn-north-1.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1.0/voice/tts (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F30730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2020-05-01 14:01:09,303] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis.cn-north-1.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1.0/voice/tts (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F30628>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2020-05-01 14:01:09,317] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis.cn-north-1.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1.0/voice/tts (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03F306A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2020-05-01 14:01:09,318] - [ERROR] - [POST Response is empety, url is https://sis.cn-north-1.myhuaweicloud.com/v1.0/voice/tts]
